### ISSUE TITLE
Add Eslint

### ISSUE THREAD

**Issue by Shucach** [Shucach/Quick-Start-Gulp#20]

**Comment by TaylorBeeston** [comment]
I'd be happy to get ESLint/Prettier set up for you, would you like to follow the [Airbnb Style Guide?](https://github.com/airbnb/javascript)

**Comment by Shucach** [comment]
> I'd be happy to get ESLint/Prettier set up for you, would you like to follow the [Airbnb Style Guide?](https://github.com/airbnb/javascript)
Yes, I will try, I think it`s will well practice. Thanks.

**Comment by TaylorBeeston** [comment]
See #21
